# Generated by Django 4.2.5 on 2023-09-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artists",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("birth_place", models.CharField()),
                ("birth_date", models.DateField()),
                ("info", models.CharField()),
                ("education", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitionHalls",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("adress", models.CharField()),
                ("phone", models.CharField()),
                ("space", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Exhibitions",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("AR", "Art"), ("AP", "Applied"), ("SC", "Sculpture")],
                        default="AR",
                        max_length=2,
                    ),
                ),
                (
                    "exhibition_hall_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.exhibitionhalls",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owners",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("adress", models.CharField()),
                ("phone", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CI", "City organization"),
                            ("RE", "Regional organization"),
                            ("PU", "Public organization"),
                            ("PR", "Private organization"),
                        ],
                        default="PU",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exhibits",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField()),
                ("date", models.DateField()),
                ("size", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PA", "Painting"),
                            ("SC", "Sculpture"),
                            ("AR", "Architecture"),
                        ],
                        default="PA",
                        max_length=2,
                    ),
                ),
                (
                    "artist_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.artists",
                    ),
                ),
                (
                    "exhibition_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.exhibitions",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exhibitionhalls",
            name="owner_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.owners",
            ),
        ),
    ]
