# Generated by Django 4.2.5 on 2023-11-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('birth_place', models.CharField()),
                ('birth_date', models.DateField(null=True)),
                ('info', models.CharField()),
                ('education', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('adress', models.CharField()),
                ('phone', models.CharField()),
                ('type', models.CharField(choices=[('CI', 'City organization'), ('RE', 'Regional organization'), ('PU', 'Public organization'), ('PR', 'Private organization')], default='PU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionHall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('adress', models.CharField()),
                ('phone', models.CharField()),
                ('space', models.CharField()),
                ('date', models.DateField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('AR', 'Art'), ('AP', 'Applied'), ('SC', 'Sculpture')], default='AR', max_length=2)),
                ('start_date', models.DateField(null=True)),
                ('exhibition_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exhibitionhall')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('date', models.DateField(null=True)),
                ('size', models.CharField()),
                ('type', models.CharField(choices=[('PA', 'Painting'), ('SC', 'Sculpture'), ('AR', 'Architecture')], default='PA', max_length=2)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.artist')),
                ('exhibitions', models.ManyToManyField(to='main.exhibition')),
            ],
        ),
    ]
