# Generated by Django 4.2.5 on 2023-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
