# Generated by Django 4.2.5 on 2023-09-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_artists_id_alter_exhibitionhalls_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitions",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
