# Generated by Django 4.2.5 on 2023-10-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_exhibitions_date_exhibitions_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="exhibits", name="exhibition_id",),
        migrations.AddField(
            model_name="exhibits",
            name="exhibitions",
            field=models.ManyToManyField(to="main.exhibitions"),
        ),
    ]
