version: "3.9"

services:
  app:
    container_name: pbz-lab2-app
    build:
      context: .
      network: host
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./exhibitions:/usr/src/exhibitions
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: pbz-lab2-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

